
E1 = "current_expiry_date key not found in NSE_DATA_DICT"
E2 = "Last_price key not found in NSE_DATA_DICT"
E2 = "NSE_DATA_DICT IS empty return"

#FILE
E3 = "FILE PATH NOT FOUND"
E4 = "NSE_DATA_DICT IS empty return"
E5 = "ANGEL ONE CUSTOM CREATE JSON FILE NOT FOUND, PLEASE CHECK FILE NOT GENRATED FOR THAT DATE"
E6 = "TOK_DF name DATAFRAME VARIABLE RETURN EMPTY"
E7 = "ANGEL_INSTRUMENT_LIST DATA NOT FETCHING FROM WEB URL"